### ISSUE TITLE
Create LiveCD

### ISSUE THREAD

**Issue by gbraad** [gbraad/minishift-atomic-iso#1]
Generation of a Atomic LiveCD for use with Minishift

Ref: https://pagure.io/atomic-wg/issue/289

**Comment by gbraad** [comment]
Hi @cgwalters @rvykydal, at the moment I am trying to use livemedia-creator to generate a livecd image with CentOS Atomic. I run it on F25 and using the following files: https://gist.github.com/gbraad/a816bf7dd1d361473eff54a5b0d6d2ca For some reason it fails. I would also prefer to run it without `--no-virt` but it wants me to use an installer image... which one?

**Comment by cgwalters** [comment]
I'd need to refresh my memory on the toolchain here to help debug this.  Offhand for the `setfiles` error, presumably it's running that from the host system?  Do you not have `policycoreutils`?

**Comment by gbraad** [comment]
Wasn't there for the python bindings: just did `dnf install -y policycoreutils-python`. re-running...

The `setfiles` issue disappeared now, but now fails even during the ostree pull:
```
2017-06-29 02:13:28,272: Receiving objects: 24% (4531/18538) 42.3 MB
2017-06-29 02:13:28,272: Receiving objects: 24% (4532/18538) 42.3 MB
2017-06-29 02:13:28,272: Receiving objects: 24% (4533/18538) 42.3 MB
2017-06-29 02:13:28,375: Unable to init server: Could not connect: Connection refused
2017-06-29 02:13:28,438: Unable to init server: Could not connect: Connection refused
2017-06-29 02:13:28,441: Unable to init server: Could not connect: Connection refused
2017-06-29 02:13:28,667: Running anaconda failed: process '['anaconda', '--kickstart', '/media/storage/workspaces/minishift-atomic-iso/centos.ks', '--cmdline', '--dirinstall', '--remotelog', '127.0.0.1:41583']' exited with status 1
2017-06-29 02:13:29,092: failed to unmount /mnt/sysimage. retrying (1/3)...
2017-06-29 02:13:30,155: failed to unmount /mnt/sysimage. retrying (2/3)...
2017-06-29 02:13:31,199: Cleanup of /mnt/sysimage failed. See program.log for details
2017-06-29 02:13:31,202: failed to unmount /mnt/sysimage. retrying (1/3)...
2017-06-29 02:13:32,235: failed to unmount /mnt/sysimage. retrying (2/3)...
2017-06-29 02:13:33,279: Cleanup of /mnt/sysimage failed. See program.log for details
2017-06-29 02:13:33,279: Install failed: novirt_install cleanup of anaconda mounts failed.
2017-06-29 02:13:33,280: Removing bad disk image
2017-06-29 02:13:33,310: ERROR: Image creation failed: novirt_install cleanup of anaconda mounts failed.
```

**Comment by gbraad** [comment]
Running with virt-install and the centos-atomic-installer.iso failed too

```
18:03:49,883 INFO program:Running... xfs_freeze -u /
18:03:49,915 ERR program:Error running xfs_freeze: No such file or directory
18:03:49,915 ERR blivet:failed to run xfs_freeze: [Errno 2] No such file or directory
18:03:49,915 INFO anaconda:bootloader.py: used boot args: crashkernel=auto
18:03:49,916 INFO program:Running... grub2-mkconfig -o /boot/grub2/grub.cfg
18:03:50,599 ERR kernel:[ 1093.345188] blk_update_request: I/O error, dev fd0, sector 0
18:03:50,599 ERR kernel:blk_update_request: I/O error, dev fd0, sector 0
18:03:50,653 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/05efi on mounted /dev/sda1
18:03:50,656 NOTICE logger:05efi: debug: Not on UEFI platform
18:03:50,656 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/10freedos on mounted /dev/sda1
18:03:50,658 NOTICE logger:10freedos: debug: /dev/sda1 is not a FAT partition: exiting
18:03:50,659 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/10qnx on mounted /dev/sda1
18:03:50,661 NOTICE logger:10qnx: debug: /dev/sda1 is not a QNX4 partition: exiting
18:03:50,662 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/20macosx on mounted /dev/sda1
18:03:50,664 NOTICE macosx-prober:debug: /dev/sda1 is not an HFS+ partition: exiting
18:03:50,665 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/20microsoft on mounted /dev/sda1
18:03:50,667 NOTICE logger:20microsoft: debug: /dev/sda1 is not a MS partition: exiting
18:03:50,668 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/30utility on mounted /dev/sda1
18:03:50,670 NOTICE logger:30utility: debug: /dev/sda1 is not a FAT partition: exiting
18:03:50,671 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/40lsb on mounted /dev/sda1
18:03:50,673 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/70hurd on mounted /dev/sda1
18:03:50,675 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/80minix on mounted /dev/sda1
18:03:50,678 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/83haiku on mounted /dev/sda1
18:03:50,680 NOTICE logger:83haiku: debug: /dev/sda1 is not a BeFS partition: exiting
18:03:50,681 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/90linux-distro on mounted /dev/sda1
18:03:50,692 NOTICE logger:os-prober: debug: running /usr/libexec/os-probes/mounted/90solaris on mounted /dev/sda1
18:03:50,712 INFO program:Generating grub configuration file ...
18:03:50,712 INFO program:Found linux image: /boot/vmlinuz-3.10.0-514.21.2.el7.x86_64-00d5f57f93f35b521df806ed94cd1aa73a0d6fde4cd36dd9eebce6b7a535f75c
18:03:50,712 INFO program:done
18:03:50,712 DEBUG program:Return code: 0
18:03:50,715 INFO program:Running... xfs_freeze -f /
18:03:50,722 ERR program:Error running xfs_freeze: No such file or directory
18:03:50,722 ERR blivet:failed to run xfs_freeze: [Errno 2] No such file or directory
18:03:50,722 INFO program:Running... xfs_freeze -u /
18:03:50,728 ERR program:Error running xfs_freeze: No such file or directory
18:03:50,728 ERR blivet:failed to run xfs_freeze: [Errno 2] No such file or directory
18:03:50,729 INFO anaconda:Installing boot loader
18:03:50,729 INFO anaconda:Performing post-installation setup tasks
18:03:50,733 INFO program:Running... cp -r -p /mnt/sysimage/ostree/deploy/centos-atomic-host/deploy/29be774ad2b95184a5066a4f113c80ceedaaedc6ccc7ae755cca5dd664d98667.0/usr/etc/ostree/remotes.d/centos-atomic-host.conf /mnt/sysimage/ostree/deploy/centos-atomic-host/deploy/29be774ad2b95184a5066a4f113c80ceedaaedc6ccc7ae755cca5dd664d98667.0/etc/ostree/remotes.d/centos-atomic-host.conf
18:03:50,740 DEBUG program:Return code: 0
18:03:50,740 INFO anaconda:Moving /mnt/sysimage/ostree/deploy/centos-atomic-host/deploy/29be774ad2b95184a5066a4f113c80ceedaaedc6ccc7ae755cca5dd664d98667.0/boot/grub2/grub.cfg -> /mnt/sysimage/ostree/deploy/centos-atomic-host/deploy/29be774ad2b95184a5066a4f113c80ceedaaedc6ccc7ae755cca5dd664d98667.0/boot/loader/grub.cfg
18:03:50,744 DEBUG anaconda:running handleException
18:03:50,744 CRIT anaconda:Traceback (most recent call last):#012#012  File "/usr/lib64/python2.7/site-packages/pyanaconda/threads.py", line 227, in run#012    threading.Thread.run(self, *args, **kwargs)#012#012  File "/usr/lib64/python2.7/threading.py", line 764, in run#012    self.__target(*self.__args, **self.__kwargs)#012#012  File "/usr/lib64/python2.7/site-packages/pyanaconda/install.py", line 270, in doInstall#012    payload.postInstall()#012#012  File "/usr/lib64/python2.7/site-packages/pyanaconda/packaging/rpmostreepayload.py", line 299, in postInstall#012    os.rename(boot_grub2_cfg, target_grub_cfg)#012#012OSError: [Errno 2] No such file or directory
```

**Comment by gbraad** [comment]
@dustymabe any updates for Atomic to allow LiveCD creation?

**Comment by Conan-Kudo** [comment]
I'd love to be able to create live media based on RPM-OSTree, particularly something like the Atomic Workstation or similar.

Not sure if this is the right place to mention my particular desire to be able to do this, but @gbraad asked me to, so here I am.

**Comment by gbraad** [comment]
@dustymabe should we discuss this further on pagure? as the usecase from @Conan-Kudo is also a very valid one.

**Comment by dustymabe** [comment]
yes, we should discuss this further on pagure: https://pagure.io/atomic-wg/issue/289
